"""empty message

Revision ID: 26bb4b9f8a66
Revises: 06eab3b01133
Create Date: 2019-12-06 14:32:41.443786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26bb4b9f8a66'
down_revision = '06eab3b01133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.drop_constraint('boards_leader_id_fkey', 'boards', type_='foreignkey')
    op.create_foreign_key(None, 'boards', 'users', ['creator_id'], ['id'])
    op.drop_column('boards', 'leader_id')
    op.add_column('teams', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'role')
    op.add_column('boards', sa.Column('leader_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'boards', type_='foreignkey')
    op.create_foreign_key('boards_leader_id_fkey', 'boards', 'users', ['leader_id'], ['id'])
    op.drop_column('boards', 'creator_id')
    # ### end Alembic commands ###
