"""empty message

Revision ID: 2f5f5eaa7325
Revises: d08a2fe03d68
Create Date: 2019-12-05 17:35:58.837346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f5f5eaa7325'
down_revision = 'd08a2fe03d68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('creator', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('duedate', sa.DateTime(timezone=True), nullable=True))
    op.add_column('tasks', sa.Column('priority', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('status', sa.String(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['creator'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'status')
    op.drop_column('tasks', 'priority')
    op.drop_column('tasks', 'duedate')
    op.drop_column('tasks', 'creator')
    # ### end Alembic commands ###
