"""empty message

Revision ID: 44575436fd51
Revises: 2335c9058a82
Create Date: 2019-12-03 16:23:30.390824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44575436fd51'
down_revision = '2335c9058a82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'user_id')
    # ### end Alembic commands ###
