"""empty message

Revision ID: 45a87ec5be5c
Revises: 4f72f6f23c86
Create Date: 2019-12-09 23:52:58.445107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45a87ec5be5c'
down_revision = '4f72f6f23c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'boards', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'boards', type_='foreignkey')
    op.drop_column('boards', 'project_id')
    # ### end Alembic commands ###
