"""empty message

Revision ID: 4f72f6f23c86
Revises: 5056351161be
Create Date: 2019-12-09 23:40:54.651334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f72f6f23c86'
down_revision = '5056351161be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('boardOrder', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_foreign_key(None, 'projects', 'users', ['creator_id'], ['id'])
    op.add_column('team_users', sa.Column('role', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('boardOrder', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('teams', 'role')
    op.add_column('users', sa.Column('boardOrder', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'boardOrder')
    op.add_column('teams', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('teams', 'timestamp')
    op.drop_column('teams', 'boardOrder')
    op.drop_column('team_users', 'role')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'timestamp')
    op.drop_column('projects', 'creator_id')
    op.drop_column('projects', 'boardOrder')
    # ### end Alembic commands ###
