"""empty message

Revision ID: 51ee1ca65603
Revises: a4f123b24f2c
Create Date: 2019-12-03 16:37:38.299454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51ee1ca65603'
down_revision = 'a4f123b24f2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
