"""empty message

Revision ID: 5382bb167504
Revises: bbaf1a581e4f
Create Date: 2019-11-26 17:07:23.921445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5382bb167504'
down_revision = 'bbaf1a581e4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('excerpt_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'scores', 'excerpts', ['excerpt_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scores', type_='foreignkey')
    op.drop_column('scores', 'excerpt_id')
    # ### end Alembic commands ###
