"""empty message

Revision ID: 6119b8eeaf46
Revises: 749aafa62aa6
Create Date: 2019-12-16 14:47:19.149797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6119b8eeaf46'
down_revision = '749aafa62aa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'boardOrder')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('boardOrder', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
