"""empty message

Revision ID: 7377c2b2f6db
Revises: 4625e7a0cfcb
Create Date: 2019-12-12 18:46:11.262831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7377c2b2f6db'
down_revision = '4625e7a0cfcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('project_type', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('parent_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'parent_id')
    op.drop_column('projects', 'project_type')
    op.drop_column('boards', 'parent_id')
    # ### end Alembic commands ###
