"""empty message

Revision ID: 749aafa62aa6
Revises: da1f8b70c39b
Create Date: 2019-12-15 00:47:34.859436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749aafa62aa6'
down_revision = 'da1f8b70c39b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'boardOrder')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('boardOrder', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
