"""empty message

Revision ID: 86e225c740f3
Revises: 62df217a8ff0
Create Date: 2019-11-26 18:17:42.981137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86e225c740f3'
down_revision = '62df217a8ff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'scores', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scores', type_='foreignkey')
    op.drop_column('scores', 'user_id')
    # ### end Alembic commands ###
