"""empty message

Revision ID: 8e333510ac3d
Revises: 7377c2b2f6db
Create Date: 2019-12-14 00:20:45.305514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e333510ac3d'
down_revision = '7377c2b2f6db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('taskOrder', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'taskOrder')
    # ### end Alembic commands ###
