"""empty message

Revision ID: 8f969f071a86
Revises: 2f5f5eaa7325
Create Date: 2019-12-05 18:00:22.946252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f969f071a86'
down_revision = '2f5f5eaa7325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.drop_constraint('tasks_creator_fkey', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['creator_id'], ['id'])
    op.drop_column('tasks', 'creator')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('creator', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_creator_fkey', 'tasks', 'users', ['creator'], ['id'])
    op.drop_column('tasks', 'creator_id')
    # ### end Alembic commands ###
