"""empty message

Revision ID: a4d5df8fd3b1
Revises: 51ee1ca65603
Create Date: 2019-12-03 16:43:24.208662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4d5df8fd3b1'
down_revision = '51ee1ca65603'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_role_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_role_fkey', 'users', 'roles', ['role'], ['id'])
    # ### end Alembic commands ###
