"""empty message

Revision ID: a8a9ac9a005c
Revises: 5d8cad1f7f20
Create Date: 2019-11-26 16:52:35.862232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8a9ac9a005c'
down_revision = '5d8cad1f7f20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('scores_user_id_fkey', 'scores', type_='foreignkey')
    op.drop_column('scores', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scores', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('scores_user_id_fkey', 'scores', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
