"""empty message

Revision ID: b7b3f7f97f93
Revises: 6119b8eeaf46
Create Date: 2019-12-16 18:43:34.753851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7b3f7f97f93'
down_revision = '6119b8eeaf46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('board_type', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('finished_board_id', sa.Integer(), nullable=True))
    op.add_column('tasks', sa.Column('progress_board_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'progress_board_id')
    op.drop_column('tasks', 'finished_board_id')
    op.drop_column('boards', 'board_type')
    # ### end Alembic commands ###
