"""empty message

Revision ID: c36b2ffbe48f
Revises: 8f969f071a86
Create Date: 2019-12-05 18:42:27.636020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c36b2ffbe48f'
down_revision = '8f969f071a86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'priority')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
