"""empty message

Revision ID: d5b5d7ca5236
Revises: 5d93e6a391d9
Create Date: 2019-12-11 10:33:45.706128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5b5d7ca5236'
down_revision = '5d93e6a391d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('creator_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teams', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'creator_id')
    # ### end Alembic commands ###
