"""empty message

Revision ID: da1f8b70c39b
Revises: e2683d8c715a
Create Date: 2019-12-14 20:11:09.510903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da1f8b70c39b'
down_revision = 'e2683d8c715a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boards', 'team_order')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('team_order', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
