"""empty message

Revision ID: e2683d8c715a
Revises: 8e333510ac3d
Create Date: 2019-12-14 16:33:08.961754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2683d8c715a'
down_revision = '8e333510ac3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boards', sa.Column('project_order', sa.Integer(), nullable=True))
    op.add_column('boards', sa.Column('team_order', sa.Integer(), nullable=True))
    op.add_column('boards', sa.Column('user_order', sa.Integer(), nullable=True))
    op.drop_column('boards', 'taskOrder')
    op.add_column('tasks', sa.Column('order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'order')
    op.add_column('boards', sa.Column('taskOrder', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('boards', 'user_order')
    op.drop_column('boards', 'team_order')
    op.drop_column('boards', 'project_order')
    # ### end Alembic commands ###
